[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/academic/*"
  to = "http://car-park-attendant-sizing-11828.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "https://sourcethemes.com/academic/"
  status = 301
