[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/academic/*"
  to = "https://wowchemy.com/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "https://wowchemy.com/"
  status = 301
  force = true
